
# H2 Database
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Connection pool
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.connection-timeout=2000

# JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Disable devtools restart
spring.devtools.restart.enabled=false

# Disable lazy init
spring.main.lazy-initialization=false


# Default level
logging.level.root=INFO

# Your package logs
logging.level.org.example.bankingapp=DEBUG

# Hibernate logs (quiet)
logging.level.org.hibernate.SQL=ERROR
logging.level.org.hibernate.type.descriptor.sql=ERROR
